---
# tasks file for vagrant
  - name: "config change in ansible.cfg"
    lineinfile:
     dest: /etc/ansible/ansible.cfg
     line: 'deprecation_warnings = False'
     insertafter: '\[defaults\]'
     backup: yes
    become: true
  - name: "Adding APT keys for Docker"
    apt_key: url="{{ item }}" state=present
    with_items:
     - 'https://download.docker.com/linux/ubuntu/gpg'
    when: "ansible_distribution == 'Ubuntu'"
    become: true
  - name: "Adding APT keys for Mongodb"
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0C49F3730359A14518585931BC711F9BA15703C6
    when: "ansible_distribution == 'Ubuntu'"
    become: true
  - name: "Adding  additional repositories"
    apt_repository: repo="{{ item }}" state=present
    with_items:
     - 'deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse'
     - 'deb https://download.docker.com/linux/ubuntu xenial stable'
     - 'ppa:deadsnakes/ppa'
     - 'ppa:openjdk-r/ppa'
    when: "ansible_distribution == 'Ubuntu'"
    become: true
  - name: "Installing packages"
    apt: pkg="{{ item }}" update_cache=yes state=present
    with_items:
     - docker-ce
     - wget
     - curl
     - git
     - tmux
     - samba
     - whois
     - samba-client
     - samba-common
     - dos2unix
     - cifs-utils
     - mongodb-org-shell
     - mongodb-org-tools
     - python3.6
     - openjdk-8-jdk
    when: "ansible_distribution == 'Ubuntu'"
    become: true

    notify:
     - start docker
     - start samba
